import { Product } from './types';

export const INITIAL_PRODUCTS: Omit<Product, 'id'>[] = [
  { name: 'AÇAFRÃO 20G', type: 'comum', active: true },
  { name: 'ALECRIM 10G', type: 'comum', active: true },
  { name: 'ALFAZEMA 10G', type: 'comum', active: true },
  { name: 'ALHO 100G', type: 'comum', active: true },
  { name: 'ALHO FRITO 20G', type: 'comum', active: true },
  { name: 'AMACIANTE DE CARNE 20G', type: 'comum', active: true },
  { name: 'AMENDOIM 20G', type: 'comum', active: true },
  { name: 'ANIS ESTRELADO 20G', type: 'comum', active: true },
  { name: 'BICARBONATO 25G', type: 'comum', active: true },
  { name: 'BOLDO 10G', type: 'comum', active: true },
  { name: 'CAMOMILA 10G', type: 'comum', active: true },
  { name: 'CANELA EM CASCA 10G', type: 'comum', active: true },
  { name: 'CASTANHA DE CAJU 25G', type: 'comum', active: true },
  { name: 'CHIA 100G ADESIVO', type: 'adesivo', active: true },
  { name: 'CHIMICHURRI 10G', type: 'comum', active: true },
  { name: 'COLORAU 50G', type: 'comum', active: true },
  { name: 'COLORAU 80G', type: 'comum', active: true },
  { name: 'COLORAU 150G', type: 'comum', active: true },
  { name: 'COLORAU 300G ADESIVO', type: 'adesivo', active: true },
  { name: 'COMINHO EM GRÃO 20G', type: 'comum', active: true },
  { name: 'COMINHO MOÍDO 25G', type: 'comum', active: true },
  { name: 'COMINHO MOÍDO 40G', type: 'comum', active: true },
  { name: 'CONFEITO DE CHOCOLATE 25G', type: 'comum', active: true },
  { name: 'CONFEITO DE CHOCOLATE 70G ADESIVO', type: 'adesivo', active: true },
  { name: 'CONFEITO PARA BOLO 25G', type: 'comum', active: true },
  { name: 'CONFEITO PARA BOLO 70G ADESIVO', type: 'adesivo', active: true },
  { name: 'CRAVINHO 10G', type: 'comum', active: true },
  { name: 'CURRY 20G', type: 'comum', active: true },
  { name: 'ENXOFRE 20G', type: 'comum', active: true },
  { name: 'ERVA CIDREIRA 20G', type: 'comum', active: true },
  { name: 'ERVA-DOCE 10G', type: 'comum', active: true },
  { name: 'FARINHA DE ROSCA 100G', type: 'comum', active: true },
  { name: 'FARINHA DE TAPIOCA ADESIVO 200G', type: 'adesivo', active: true },
  { name: 'GENGIBRE 20G', type: 'comum', active: true },
  { name: 'HIBISCO 10G', type: 'comum', active: true },
  { name: 'LEMON PEPPER 20G', type: 'comum', active: true },
  { name: 'LINHAÇA DOURADA 20G', type: 'comum', active: true },
  { name: 'LINHAÇA MARROM 20G', type: 'comum', active: true },
  { name: 'LOURO 10G', type: 'comum', active: true },
  { name: 'MACA PERUANA 20G', type: 'comum', active: true },
  { name: 'MILHO BRANCO 300G ADESIVO', type: 'adesivo', active: true },
  { name: 'MILHO DE PIPOCA 80G', type: 'comum', active: true },
  { name: 'MILHO DE PIPOCA 150G', type: 'comum', active: true },
  { name: 'MILHO DE PIPOCA 300G ADESIVO', type: 'adesivo', active: true },
  { name: 'OREGANO 10G', type: 'comum', active: true },
  { name: 'PÁPRICA DEFUMADA 20G', type: 'comum', active: true },
  { name: 'PÁPRICA DOCE 20G', type: 'comum', active: true },
  { name: 'PÁPRICA PICANTE 20G', type: 'comum', active: true },
  { name: 'PICADINHO DE SOJA ADESIVO 200G', type: 'adesivo', active: true },
  { name: 'PIMENTA CALABRESA', type: 'comum', active: true },
  { name: 'PIMENTA COM COMINHO 25G', type: 'comum', active: true },
  { name: 'PIMENTA COM COMINHO 40G', type: 'comum', active: true },
  { name: 'PIMENTA DO REINO MOÍDA 20G', type: 'comum', active: true },
  { name: 'PIMENTA DO REINO MOÍDA 40G', type: 'comum', active: true },
  { name: 'PIMENTA EM GRÃO 20G', type: 'comum', active: true },
  { name: 'PISTACHE 20G', type: 'comum', active: true },
  { name: 'SAL GROSSO 20G', type: 'comum', active: true },
  { name: 'SEMENTE DE ABÓBORA 20G', type: 'comum', active: true },
  { name: 'SEMENTE DE GIRASSOL', type: 'comum', active: true },
  { name: 'SENE 10G', type: 'comum', active: true },
  { name: 'TEMPERO ANA MARIA BRAGA 20G', type: 'comum', active: true },
  { name: 'TEMPERO BAIANO 20G', type: 'comum', active: true },
  { name: 'TEMPERO CHEIRO VERDE ADESIVO 200G', type: 'adesivo', active: true },
  { name: 'TEMPERO COMPLETO AÇAFRÃO ADESIVO 200G', type: 'adesivo', active: true },
  { name: 'TEMPERO COMPLETO COLORAL ADESIVO 200G', type: 'adesivo', active: true },
  { name: 'TEMPERO COMPLETO DE CHURRASCO ADESIVO 200G', type: 'adesivo', active: true },
  { name: 'TEMPERO DO CHEFE 20G', type: 'comum', active: true },
  { name: 'TEMPERO PARA CHURRASCO 500G', type: 'comum', active: true },
  { name: 'UVA PASSA ADESIVO', type: 'adesivo', active: true },
];

export const WHATSAPP_NUMBER = '92955059';

export const COLORS = {
  primary: '#10b981', // emerald-500
  secondary: '#0ea5e9', // sky-500
  accent: '#f59e0b', // amber-500
};
